apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 1
network: k3d

kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"

volumes:
- volume: /workspaces:/workspaces
  nodeFilters:
  - server:*

ports:
- port: 8000:80 # same as `--port '8000:80@loadbalancer'`
  nodeFilters:
  - loadbalancer

registries:
  use:
    - k3d-registry.localhost:5500

options:
  k3d:
    wait: true
    timeout: "90s"
  k3s:
    extraArgs:
    - arg: --tls-san=127.0.0.1
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
